name: HTML5 Check
on:
  push:
    branches: [ master ]
  pull_request:
    branches: '**'

jobs:
  html_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v0.4.1
      with:
        format: gnu

